### PR TITLE
[MER-2038] fix popup block flow issue

### LINKED ISSUE #3538: Inline <anchor><extra> migrated as block
https://tokamak.oli.cmu.edu/sections/gen_chem_0412_ykrj5/page/v1q9y_ionic_bond_formation_pqu1s
image
In Torus above How it should look as in Legacy below
image

### PR DESCRIPTION
**Pull request by eliknebel**
Fixes an issue where popup elements were being rendered as block. Also replaces bootstrap popup with react tiny popover since the existing bootstrap code wasn't reliably working. Finally, allows better control over audio content within a popup by using the click to play/pause while still allowing a student to read the content of a popup.

Closes #3538

### CODE REVIEW

File: lib/oli/rendering/content/html.ex [hunk 1]
```diff
@@ -698,9 +704,13 @@ defmodule Oli.Rendering.Content.Html do
...
     {:safe, rendered} =
-      ReactPhoenix.ClientSide.react_component("Components.DeliveryElementRenderer", %{
-        "element" => element
-      })
+      ReactPhoenix.ClientSide.react_component(
+        "Components.DeliveryElementRenderer",
+        %{
+          "element" => element
+        },
+        html_element: "span"
```
Comment (eliknebel) [inline lib/oli/rendering/content/html.ex:712]: Using a span here was one piece to getting this content to flow inline properly

File: lib/oli/rendering/content/html.ex [hunk 2]
```diff
@@ -76,15 +76,21 @@ defmodule Oli.Rendering.Content.Html do
   end
 
   def ecl(%Context{} = context, _, attrs) do
-
-    attempt_guid = case context.resource_attempt do
-      nil -> ""
-      attempt -> attempt.attempt_guid
-    end
+    attempt_guid =
```
Comment (eliknebel) [inline lib/oli/rendering/content/html.ex:79]: Auto formatter changes

File: assets/src/data/content/writers/renderer.tsx [hunk 3]
```diff
@@ -7,15 +7,10 @@ import { ContentWriter } from './writer';
...
 export const HtmlContentModelRenderer: React.FC<Props> = (props) => {
   // Support content persisted when RichText had a `model` property.
   const content = (props.content as any).model ? (props.content as any).model : props.content;
 
-  return (
-    <div style={props.style}>
-      {new ContentWriter().render(props.context, content, new HtmlParser())}
-    </div>
-  );
+  return <>{new ContentWriter().render(props.context, content, new HtmlParser())}</>;
```
Comment (eliknebel) [inline assets/src/data/content/writers/renderer.tsx:15]: Rendering content inside a react fragement instead of a div is necessary to allow inline elements to be rendered properly. e.g. `<p></p>` technically cannot contain a `<div></div>`

File: lib/oli_web/components/delivery/nav_sidebar.ex [hunk 4]
```diff
@@ -19,7 +19,7 @@ defmodule OliWeb.Components.Delivery.NavSidebar do
 
   def main_with_nav(assigns) do
     ~H"""
-      <main role="main" class="h-screen flex flex-col relative lg:flex-row z-0">
+      <main role="main" class="flex flex-col relative lg:flex-row z-0">
```
Comment (eliknebel) [inline lib/oli_web/components/delivery/nav_sidebar.ex:22]: Removing h-screen was necessary to get popups to render in the correct location, I think it was a leftover mistake style here anyways

File: lib/oli_web/components/delivery/nav_sidebar.ex [hunk 5]
```diff
@@ -88,17 +88,19 @@ defmodule OliWeb.Components.Delivery.NavSidebar do
...
     ]
     |> then(fn links ->
       case section do
         %Section{contains_explorations: true} ->
-          links ++ [%{
-            name: "Exploration",
-            href: "#",
-            active: false
-          }]
+          links ++
```
Comment (eliknebel) [inline lib/oli_web/components/delivery/nav_sidebar.ex:96]: Auto formatting

**Review by darrensiegel — APPROVED** [review]
