### PR TITLE
[BUG] [MER-1403] [#2918] MathJax config fix.

### LINKED ISSUE #2918: Latex rendering not configured correctly to render all Latex commands
1. Create a Latex Formula in a page.
2. Use the following source:

```
\require{cancel}\mathrm{mol}\;\mathrm{HCl}\;\mathrm{produced}\;=\;3\;\cancel{\mathrm{mol}\;{\mathrm H}_2}\;\times\;\frac{2\;\mathrm{mol}\;\mathrm{HCl}}{1\;\cancel{\mathrm{mol}\;{\mathrm H}_2}}\;\;=\;6\;\mathrm{mol}\;\mathrm{HCl}
```

In authoring, preview and delivery this formula incorrectly renders as:

Screen Shot 2022-08-11 at 8 41 35 AM

### PR DESCRIPTION
**Pull request by marc-hughes**
Fixes #2918

A tweak to our mathjax configuration to support the \require command which lets the \cancel command work in this sample formula.

```
\require{cancel}\mathrm{mol}\;\mathrm{HCl}\;\mathrm{produced}\;=\;3\;\cancel{\mathrm{mol}\;{\mathrm H}_2}\;\times\;\frac{2\;\mathrm{mol}\;\mathrm{HCl}}{1\;\cancel{\mathrm{mol}\;{\mathrm H}_2}}\;\;=\;6\;\mathrm{mol}\;\mathrm{HCl}
```

After fix applied:

image

While at it, I put this config in a phoenix component since it was copy/pasted in 3 different html files.

### CODE REVIEW

File: lib/oli_web/common/mathjax_script.ex [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+
+  def render(assigns) do
+    ~H"""
+    <script>
+    window.MathJax = {
+      tex: {
+        inlineMath: [ ["\\(","\\)"] ],
+        displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
+        processEscapes: true,
+        packages: ['base', 'ams', 'noerrors', 'noundefined', 'require']
```
Comment (marc-hughes) [inline lib/oli_web/common/mathjax_script.ex:12]: The only real change to the config was adding 'require' here

**Review by bsparks — APPROVED** [review]

**Comment by marc-hughes** [comment]
🚨 Don't merge this in yet.

Found a bug where if you're typing \require{cancel} instead of copy/pasting it in, you'll hit an error because it tries to load the "C" extension that doesn't exist.

**Comment by marc-hughes** [comment]
> Found a bug where if you're typing \require{cancel} instead of copy/pasting it in, you'll hit an error because it tries to load the "C" extension that doesn't exist.

Supplying the list of valid extensions to the require extension fixed this.

**Review by darrensiegel — APPROVED** [review]
