### PR TITLE
[BUG FIX] Remove extra checkbox for enabling LMS-lite section creation

### LINKED ISSUE #1999: LMS-Lite Institution Instructor checkbox doesn't always change
**Describe the bug**
Institution Instructor checkbox doesn't always change, see attached video

**To Reproduce**
1. Go to LMS-Lite options for an independent section
2. Click on Institution Instructor checkbox
4. See strange behavior

**Screenshots**

https://user-images.githubusercontent.com/6248894/146281166-065f1e17-8b5f-47f1-a610-d50451963d12.mov

**Environment (please complete the following information):**
 - OS: macOS 12.0.1
 - Browser: Chrome
 - Version: 96

### PR DESCRIPTION
**Pull request by LEDThereBeLight**
Two changes:
- Remove second (institution instructor) checkbox from the admin panel when enabling delivery users to create lms-lite/independent sections. This was in place originally as a safety measure to work with some code that checked for the "institution instructor" platform role, but I realized it's not needed.
- Add a link in the delivery account dropdown menu to link an authoring account

No changelog since this is an unreleased feature.

Closes #1999

### CODE REVIEW

File: lib/oli_web/live/users/user_detail_view.ex [hunk 1]
```diff
@@ -82,35 +77,23 @@ defmodule OliWeb.Users.UsersDetailView do
...
                 <Label class="form-check-label mr-2">Independent Learner</Label>
               </Field>
             </div>
 
-            <section>
+            <section class="mb-2">
               <heading>
-                <p>Enable LMS-Lite Section Creation <small>(check both)</small></p>
+                <p>Enable Independent Section Creation</p>
+                <small>This ability allows delivery users to create and deliver "Independent" sections through OLI without a connected LMS, either Open and Free or limited to students who enroll through an invitation link.</small>
```
Comment (eliknebel) [inline lib/oli_web/live/users/user_detail_view.ex:90]: I think we need to remove the reference to OLI here. Maybe something like:

"Allow this user to create "Independent" sections and enroll students via invitation link without an LMS"

**Review by eliknebel — APPROVED** [review]

**Review by eliknebel — CHANGES_REQUESTED** [review]
Accidentally approved, see comments above

**Review by eliknebel — APPROVED** [review]
