### PR TITLE
Fix CATA/Ordering activity submission in delivery

### LINKED ISSUE #797: Check all that apply doesn't seem to submit in graded assessment
**Describe the bug**
Check all that apply doesn't always submit in graded assessment.

**To Reproduce**
1. Go to a check all that apply in a Graded Assessment in delivery
2. Complete the assessment and submit
3. Review the attempt and see no grade for the check all that apply

**Expected behavior**
Check all that apply should submit and be show in attempt review

**Screenshots**
Screen Shot 2021-02-19 at 8 57 37 PM

**Environment (please complete the following information):**
 - OS: macOS 11.2.1
 - Browser chrome
 - Version 88

### LINKED ISSUE #906: Ordering activity doesn't work correctly in graded assessment
**Describe the bug**
When submitting a graded assessment with an ordering activity, the displayed response does not represent the response actually selected by a student. 

**To Reproduce**
1. Got to a graded assessment with an ordering question
2. Complete the ordering question and submit the assessment
3. See that the response recorded is not the same that was submitted

**Expected behavior**
Ordering should correctly evaluate and display results

**Screenshots**
Screen Shot 2021-04-06 at 1 31 35 PM

Screen Shot 2021-04-06 at 1 31 45 PM

**Additional context**
This was identified in an open and free section, but it also appears to be an issue in an lti section as well.

### PR DESCRIPTION
**Pull request by LEDThereBeLight**
CATA/Ordering questions answered correctly were being marked wrong in delivered courses because the `onSelect` function used to "save" an a student's choice used a React state variable that wasn't updated before running the `onSaveActivity` persistence function.

Auto lint on save also picked up some formatting changes.

Closes #797 
Closes #906

### CODE REVIEW

File: assets/src/components/activities/check_all_that_apply/CheckAllThatApplyDelivery.tsx [hunk 1]
```diff
@@ -65,21 +66,22 @@ const CheckAllThatApply = (props: DeliveryElementProps<CheckAllThatApplyModelSch
...
+      : props.state.parts[0].response.input.split(' ')
+        .reduce(
+          (acc: ActivityTypes.ChoiceId[], curr: ActivityTypes.ChoiceId) => acc.concat([curr]),
+          []));
 
   const { stem, choices } = model;
 
   const isEvaluated = attemptState.score !== null;
-  const selectedToInput = () => selected.join(' ');
+  const selectionToInput = (newSelection: string | undefined) =>
```
Comment (LEDThereBeLight) [inline assets/src/components/activities/check_all_that_apply/CheckAllThatApplyDelivery.tsx:78]: Change to allow the "new" selection to be added to the existing selection so that a new selection can be saved before the react state is updated.

File: assets/src/components/activities/check_all_that_apply/CheckAllThatApplyDelivery.tsx [hunk 2]
```diff
@@ -106,46 +108,46 @@ const CheckAllThatApply = (props: DeliveryElementProps<CheckAllThatApplyModelSch
     // Then in the rule evaluator, we will say
     // `input like id1 && input like id2 && input like id3`
     props.onSaveActivity(attemptState.attemptGuid,
-      [{ attemptGuid: attemptState.parts[0].attemptGuid, response: { input: selectedToInput() } }]);
+      [{ attemptGuid: attemptState.parts[0].attemptGuid, response: { input: selectionToInput(id) } }]);
```
Comment (LEDThereBeLight) [inline assets/src/components/activities/check_all_that_apply/CheckAllThatApplyDelivery.tsx:111]: main fix is here

**Review by eliknebel — CHANGES_REQUESTED** [review]
Looks good, fixes the submission issue. But I think there is still an issue preventing the feedback from being displayed

Screen Shot 2021-04-07 at 10 45 18 AM

**Comment by eliknebel** [comment]
I have filed a separate bug for the feedback issue https://github.com/Simon-Initiative/oli-torus/issues/912

**Comment by eliknebel** [comment]
I believe the ordering issue is related to this https://github.com/Simon-Initiative/oli-torus/issues/906. Can we incorporate the same fix for the ordering in this PR as well?

File: assets/src/components/activities/ordering/OrderingDelivery.tsx [hunk 3]
```diff
@@ -110,14 +109,15 @@ const Ordering = (props: DeliveryElementProps<OrderingModelSchema>) => {
   const { stem, choices } = model;
 
   const isEvaluated = attemptState.score !== null;
-  const orderedChoiceIds = () => selected.join(' ');
+  const orderedChoiceIds = (newSelection: string | undefined) =>
+    newSelection === undefined ? selected.join(' ') : selected.concat(newSelection).join(' ');
```
Comment (LEDThereBeLight) [inline assets/src/components/activities/ordering/OrderingDelivery.tsx:113]: fix #1

File: assets/src/components/activities/ordering/OrderingDelivery.tsx [hunk 4]
```diff
@@ -146,7 +146,7 @@ const Ordering = (props: DeliveryElementProps<OrderingModelSchema>) => {
     props.onSaveActivity(attemptState.attemptGuid,
       [{
         attemptGuid: attemptState.parts[0].attemptGuid,
-        response: { input: orderedChoiceIds() },
+        response: { input: orderedChoiceIds(id) },
```
Comment (LEDThereBeLight) [inline assets/src/components/activities/ordering/OrderingDelivery.tsx:149]: fix #2

**Comment by LEDThereBeLight** [comment]
> ering issue is related to this #906. Can we incorporate the same fix for the ordering in this

fixed

**Review by eliknebel — APPROVED** [review]
