### PR TITLE
[BUG FIX] Fix Activity Bugs

### LINKED ISSUE #1494: Targeted feedback for incorrect answers not showing
**Describe the bug**
When selecting an incorrect answer, the targeted feedback doesn't seem to show, instead feedback simply displays "Incorrect".

**To Reproduce**
1. Go to a graded assessment with targeted feedback for an incorrect answer
2. Select the incorrect answer and submit the assessment. Then review the assessment.
3. See the feedback displayed does not match the targeted feedback set.

**Expected behavior**
Targeted feedback should be displayed when it is set.

**Screenshots**
Screen Shot 2021-09-07 at 4 41 04 PM

Screen Shot 2021-09-07 at 4 42 15 PM

**Environment (please complete the following information):**
 - OS: macOS 11.5
 - Browser: Chrome 92

### LINKED ISSUE #1497: Clicking on checkbox in CATA authoring doesn't unselect
**Describe the bug**
Clicking on checkbox in CATA authoring doesn't mark as correct as unselected. Once these checkboxes are selected, they are rendered as readonly which prohibits them from being unchecked.

**To Reproduce**
1. Go to check all that apply in authoring page
2. Select "Answers" and try to unselect a correct item using the checkbox icon

**Expected behavior**
Answers should be unselectable using the checkbox, as this is how user will expect to use the feature and is also how multiple choice works.

**Screenshots**
Screen Shot 2021-09-07 at 4 31 53 PM

**Environment (please complete the following information):**
 - OS: macOS 11.5
 - Browser: Chrome 92

### LINKED ISSUE #1523: Display of answer options have differently-sized circles and boxes
The Check all that apply and MCQ question type options show different sized squares and circles respectively.

Create a CATA or MCQ with answer options of various lengths and preview. The long the text in the option, the smaller the choice selector appears.

**Expected behavior*
answer option selectors should all be the same size regardless of the amount of text.
**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. iOS] iOS
 - Browser: [e.g. chrome, safari] Chrome
 - Version: [e.g. 22] Version 93.0.4577.63 (Official Build) (x86_64)

Screen Shot 2021-09-15 at 11 13 43 AM
Screen Shot 2021-09-15 at 11 10 29 AM

### LINKED ISSUE #1524: Targeted Feedback is not displaying
**Describe the bug**
In MCQ's, targeted feedback is not displaying.

**To Reproduce**
Create an MCQ with targeted feedback for any specific answer option. 
Preview or publish

**Expected behavior**
Targeted feedback should show when that answer is selected.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. iOS] iOS
 - Browser: [e.g. chrome, safari] Chrome
 - Version: [e.g. 22] Version 93.0.4577.63 (Official Build) (x86_64)

Screen Shot 2021-09-15 at 12 31 12 PM
Screen Shot 2021-09-15 at 12 30 59 PM

https://canvas.oli.cmu.edu/courses/259/modules/items/374
https://proton.oli.cmu.edu/authoring/project/the_cuisine_of_northern_spain_/resource/cuisine_of_asturias_y9u8f
https://proton.oli.cmu.edu/authoring/project/client_project/preview/preassessment_saoou

### PR DESCRIPTION
**Pull request by LEDThereBeLight**
1. Activity choice icons weren't clickable due to a regression
2. Answer submissions did not find incorrect / targeted feedback with a score of 0
3. Sizes of choice radio/checkboxes in delivery

Please test the answer submission / evaluator logic. I tested with a few activity types but I don't know the reason why the initial scores were changed from `-1` to `0` a few days ago, so I want to make sure I'm not missing something.

Closes #1494 
Closes #1497 
Closes #1523 
Closes #1524

### CODE REVIEW

File: assets/src/components/activities/check_all_that_apply/CheckAllThatApplyAuthoring.tsx [hunk 1]
```diff
@@ -50,7 +50,7 @@ const CheckAllThatApply = () => {
       <TabbedNavigation.Tab label="Answer Key">
         <AnswerKey
           selectedChoiceIds={getCorrectChoiceIds(model)}
-          selectedIcon={<Checkbox.Correct />}
+          selectedIcon={<Checkbox.Checked />}
```
Comment (LEDThereBeLight) [inline assets/src/components/activities/check_all_that_apply/CheckAllThatApplyAuthoring.tsx:53]: Style changes in some other branch changed these icons

File: lib/oli/delivery/evaluation/evaluator.ex [hunk 2]
```diff
@@ -9,7 +9,7 @@ defmodule Oli.Delivery.Evaluation.Evaluator do
   evaluation, returns the feedback and a scoring result.
   """
   def evaluate(%Part{} = part, %EvaluationContext{} = context) do
-    case Enum.reduce(part.responses, {context, nil, 0, 0}, &consider_response/2) do
+    case Enum.reduce(part.responses, {context, nil, -1, -1}, &consider_response/2) do
```
Comment (darrensiegel) [inline lib/oli/delivery/evaluation/evaluator.ex:12]: This needs to remain -1, -1, otherwise "Response-less" activiites (e.g. ones that use client-side evaluation) that haven't been submitted will display "0 out of -1" points.

**Review by darrensiegel — CHANGES_REQUESTED** [review]

File: lib/oli/delivery/evaluation/evaluator.ex (hunk 2 above)
Comment (LEDThereBeLight) [reply lib/oli/delivery/evaluation/evaluator.ex:12]: The trouble with the scores starting at `0` is that the `evaluate` logic only uses matching responses that have a **greater** score, meaning the way it worked before is that if the student's answer is incorrect, it updates the responses with the first matching targeted feedback. If we change the logic to allow responses with scores **greater than or equal to** the current score, it will take the last catch-all response instead.

There's probably a way to change it so it takes the first response that is at least the current score, I'll think about it after the multi input is wrapped up.

**Review by darrensiegel — APPROVED** [review]
I tested with the image coding activity and scores are being calculated correctly.  This was the case drove the changing of initial scores.
